---
minio_server_group: minio
minio_server_user: "{{ minio_server_group }}"
minio_server_home: "/opt/{{ minio_server_user }}"
minio_server_certs_dir: "{{ minio_server_home }}/certs"
minio_server_data_dir: "{{ minio_server_home }}/data"
minio_env_file: "{{ minio_server_home }}/minio.env"

minio_server_kes_client_key: "{{ minio_server_certs_dir }}/kes-client.key"
minio_server_kes_client_cert: "{{ minio_server_certs_dir }}/kes-client.crt"
minio_server_kes_client_ca: "{{ minio_server_certs_dir }}/CAs/kes-ca.crt"

minio_server_cert: "{{ minio_server_certs_dir }}/public.crt"
minio_server_key: "{{ minio_server_certs_dir }}/private.key"
minio_server_ca: "{{ minio_server_certs_dir }}/CAs/server-ca.crt"

minio_server_container_name: minio-server

minio_server_hostnames: ["localhost"]
minio_server_hostname: "{{ minio_server_hostnames | first }}"
minio_server_ips: ["127.0.0.1"]
minio_server_ip: "{{ minio_server_ips | first }}"
minio_server_port: 9000
minio_server_console_port: 9001
# minio_server_root_user:
# minio_server_root_password:
minio_server_systemd_service_name: minio.service

minio_server_bin_info_map:
    x86_64:
        minio_server_arch: amd64
        sha256sum:
            "RELEASE.2024-05-10T01-41-38Z": bd3a3e65c48d35613fe1c556e77a18bccb8aee911b6293ca5f6112f73376c105
    aarch64:
        minio_server_arch: arm64
        sha256sum:
            "RELEASE.2024-05-10T01-41-38Z": b830c0862eadd2adb0db07118858fb917ac8002a9fde7a8eb0cc5234699ba40d
minio_server_version: RELEASE.2024-05-10T01-41-38Z
