---
all:
    vars:
        pv_global_config_env_debug: "{{ lookup('ansible.builtin.env', 'DEBUG', default=false) | bool }}"
    hosts:
        localhost:
            ansible_connection: local
            ansible_python_interpreter: "/usr/bin/env python3"
    children:
        kes_servers:
            vars:
                minio_kes_group: kes
                minio_kes_user: "{{ minio_kes_group }}"
                minio_kes_home: "/opt/{{ minio_kes_user }}"
                minio_kes_config_file: "{{ minio_kes_home }}/kes-config.yml"

                minio_kes_server_key: "{{ minio_kes_home }}/kes-server.key"
                minio_kes_server_cert: "{{ minio_kes_home }}/kes-server.crt"
                minio_kes_server_ca: "{{ minio_kes_home }}/kes-server-ca.crt"

                minio_kes_vault_client_cert: "{{ minio_kes_home }}/vault-client.crt"
                minio_kes_vault_client_key: "{{ minio_kes_home }}/vault-client.key"
                minio_kes_vault_ca_cert: "{{ minio_kes_home }}/vault-ca.crt"

                minio_kes_systemd_service_name: kes.service
                minio_kes_container_name: minio-kes
                minio_kes_hostnames: ["localhost"]
                minio_kes_ips: ["127.0.0.1"]
                minio_kes_port: 7373

                minio_kes_bin_info_map:
                    x86_64:
                        minio_kes_arch: amd64
                        sha256sum:
                            "2024-04-12T13-50-00Z": 1549cadb384c093ab7a9b778006a60063884b31311fc7cafd3c92f2145b9a916
                            "2024-06-17T15-47-05Z": 7646c12d83d4fb24de556a6cfc52a056165beb5d70534dd4c9db0820d48d6488
                    aarch64:
                        minio_kes_arch: arm64
                        sha256sum:
                            "2024-04-12T13-50-00Z": 251d7182df96b111008ff98f4c6bdb3b3e06ef9ea2d3b6c9fcbea9a8a80579cd
                            "2024-06-17T15-47-05Z": f37515c25cdf5152cfbe03ab32fa7eaf3f22073646668e1913ae8a4a5339c048
                minio_kes_version: 2024-06-17T15-47-05Z

        minio_servers:
            vars:
                minio_server_kes_endpoint: "https://127.0.0.1:7373"
                minio_server_group: minio
                minio_server_user: "{{ minio_server_group }}"
                minio_server_home: "/opt/{{ minio_server_user }}"
                minio_server_certs_dir: "{{ minio_server_home }}/certs"
                minio_server_data_dir: "{{ minio_server_home }}/data"
                minio_env_file: "{{ minio_server_home }}/minio.env"

                minio_server_kes_client_key: "{{ minio_server_certs_dir }}/kes-client.key"
                minio_server_kes_client_cert: "{{ minio_server_certs_dir }}/kes-client.crt"
                minio_server_kes_client_ca: "{{ minio_server_certs_dir }}/CAs/kes-ca.crt"

                minio_server_cert: "{{ minio_server_certs_dir }}/public.crt"
                minio_server_key: "{{ minio_server_certs_dir }}/private.key"
                minio_server_ca: "{{ minio_server_certs_dir }}/CAs/server-ca.crt"

                minio_server_container_name: minio-server

                minio_server_hostnames: ["localhost"]
                minio_server_ips: ["127.0.0.1"]
                minio_server_port: 9000
                minio_server_console_port: 9001
                minio_server_kes_secret_id_vault: "{{ minio_server_kes_secret_id_vault | d('inventory_hostname')
                    | mandatory }}"

                minio_server_systemd_service_name: minio.service

                minio_server_bin_info_map:
                    x86_64:
                        minio_server_arch: amd64
                        sha256sum:
                            "RELEASE.2024-05-10T01-41-38Z": bd3a3e65c48d35613fe1c556e77a18bccb8aee911b6293ca5f6112f73376c105
                            "RELEASE.2024-06-13T22-53-53Z": 1568c0d8ab09eebaf444f78ec9cd85ce62b1a2aacbd92ec29c1ec779864811bc
                    aarch64:
                        minio_server_arch: arm64
                        sha256sum:
                            "RELEASE.2024-05-10T01-41-38Z": b830c0862eadd2adb0db07118858fb917ac8002a9fde7a8eb0cc5234699ba40d
                            "RELEASE.2024-06-13T22-53-53Z": e30af0de3db096a35d594e7e7fa501efd686cb3a3335f8576f36c7359ecde5a3
                minio_server_version: RELEASE.2024-06-13T22-53-53Z

                minio_mc_bin_info_map:
                    x86_64:
                        minio_server_arch: amd64
                        sha256sum:
                            "RELEASE.2024-05-09T17-04-24Z": 360196aa51e7664996abbd3a522bdf4749188744a4d36d9bc0c4068d7dfad9e2
                            "RELEASE.2024-06-12T14-34-03Z": bc91b2e313c8715fc84dd40fb208ab5244015d7a75b8c204a5547e8ee18a6dca
                    aarch64:
                        minio_server_arch: arm64
                        sha256sum:
                            "RELEASE.2024-05-09T17-04-24Z": 3af6501fd9b36780ce6715290f84458480eada7ff4ca4d26a593ec04592bbf3d
                            "RELEASE.2024-06-12T14-34-03Z": 78682be9b33313457c86dbb7c44e0b949c39bfce40ce01c240ab4ce6b355936e
                minio_mc_version: RELEASE.2024-06-12T14-34-03Z
                minio_mc_config_dir: "{{ minio_server_home }}/.mc"
