---
all:
    vars:
        pv_global_config_env_debug: "{{ lookup('ansible.builtin.env', 'DEBUG', default=false) | bool }}"
    hosts:
        localhost:
            ansible_connection: local
            ansible_python_interpreter: "/usr/bin/env python3"
