---
- name: Prepare
  hosts: minio_servers
  gather_facts: true
  tags: always
  become: true
  timeout: 30
  gather_timeout: 30
  tasks:
      - name: Minio | KES/Server | Assert
        ansible.builtin.import_tasks:
            file: tasks/asserts.yml

      - name: Minio | KES/Server | Install
        ansible.builtin.import_tasks:
            file: tasks/install.yml
