---
- name: Prepare
  hosts: kes_servers
  gather_facts: true
  tags: never,kes_install
  become: true
  timeout: 30
  gather_timeout: 30
  tasks:
      - name: KES | Assert
        ansible.builtin.import_tasks:
            file: tasks/kes_asserts.yml

      - name: Minio | KES/Server | Install
        ansible.builtin.import_tasks:
            file: tasks/kes_install.yml
