---
- name: Minio | KES | Assert | minio_kes_hostnames
  ansible.builtin.assert:
      that:
          - minio_kes_hostnames | type_debug == 'list'
          - minio_kes_hostnames | length > 0
      fail_msg: "minio_kes_hostnames must be a list with at least one element"

- name: Minio | KES | Assert | minio_kes_ips
  ansible.builtin.assert:
      that:
          - minio_kes_ips | type_debug == 'list'
          - minio_kes_ips | length > 0
      fail_msg: "minio_kes_ips must be a list with at least one element"

- name: Minio | Server | Assert | minio_server_hostnames
  ansible.builtin.assert:
      that:
          - minio_server_hostnames | type_debug == 'list'
          - minio_server_hostnames | length > 0
      fail_msg: "minio_server_hostnames must be a list with at least one element"

- name: Minio | Server | Assert | minio_server_hostname
  ansible.builtin.assert:
      that:
          - minio_server_hostname in minio_server_hostnames
      fail_msg: "minio_server_hostname must be one of the elements in minio_server_hostnames"

- name: Minio | Server | Assert | minio_server_ips
  ansible.builtin.assert:
      that:
          - minio_server_ips | type_debug == 'list'
          - minio_server_ips | length > 0
      fail_msg: "minio_server_ips must be a list with at least one element"

- name: Minio | Server | Assert | minio_server_ip
  ansible.builtin.assert:
      that:
          - minio_server_ip in minio_server_ips
      fail_msg: "minio_server_ip must be one of the elements in minio_server_ips"

- name: Minio | Server | Assert | minio_server_root_user
  ansible.builtin.assert:
      that:
          - minio_server_root_user | type_debug in ['string', 'AnsibleUnicode']
          - minio_server_root_user | length > 5
      fail_msg: "minio_server_root_user must be a non-empty string"

- name: Minio | Server | Assert | minio_server_root_password
  ansible.builtin.assert:
      that:
          - minio_server_root_password | type_debug in ['string', 'AnsibleUnicode']
          - minio_server_root_password | length > 12
      fail_msg: minio_server_root_password must be a non-empty string and should contain at least one lowercase letter,
          one uppercase letter, one digit, one special character and should be at least 12 characters long
