---
- name: Minio | KES | Server Certificate
  become: false
  delegate_facts: true
  delegate_to: localhost
  community.hashi_vault.vault_write:
      url: "{{ hashicorp_vault_kv2_inventory.hvac_client_configuration.url }}"
      path: pki/issue/server_certificate
      token: "{{ hashicorp_vault_kv2_inventory.hvac_token }}"
      validate_certs: true
      data:
          common_name: "{{ inventory_hostname }}"
          alt_names: "{{ minio_kes_hostnames | join(',') }}"
          ip_sans: "{{ minio_kes_ips | join(',') }}"
  register: minio_kes_tmp_server_cert
  environment:
      VAULT_CACERT: "{{ hashicorp_vault_kv2_inventory.hvac_client_configuration.verify }}"
      VAULT_CLIENT_CERT: "{{ hashicorp_vault_kv2_inventory.hvac_client_configuration.cert[0] }}"
      VAULT_CLIENT_KEY: "{{ hashicorp_vault_kv2_inventory.hvac_client_configuration.cert[1] }}"

- name: Minio | Server | Admin Client Certificate
  become: false
  delegate_facts: true
  delegate_to: localhost
  community.hashi_vault.vault_write:
      url: "{{ hashicorp_vault_kv2_inventory.hvac_client_configuration.url }}"
      path: pki/issue/client_certificate
      token: "{{ hashicorp_vault_kv2_inventory.hvac_token }}"
      validate_certs: true
      data:
          common_name: "{{ inventory_hostname }}"
          alt_names: "{{ minio_kes_hostnames | join(',') }}"
          ip_sans: "{{ minio_kes_ips | join(',') }}"
  register: minio_vault_tmp_admin_client_cert
  environment:
      VAULT_CACERT: "{{ hashicorp_vault_kv2_inventory.hvac_client_configuration.verify }}"
      VAULT_CLIENT_CERT: "{{ hashicorp_vault_kv2_inventory.hvac_client_configuration.cert[0] }}"
      VAULT_CLIENT_KEY: "{{ hashicorp_vault_kv2_inventory.hvac_client_configuration.cert[1] }}"

- name: Minio | KES | Vault Client Certificate
  become: false
  delegate_facts: true
  delegate_to: localhost
  community.hashi_vault.vault_write:
      url: "{{ hashicorp_vault_kv2_inventory.hvac_client_configuration.url }}"
      path: pki/issue/vault_client_certificate
      token: "{{ hashicorp_vault_kv2_inventory.hvac_token }}"
      validate_certs: true
      data:
          common_name: "{{ hashicorp_vault_kv2_inventory.hvac_client_configuration.url | urlsplit('hostname') }}"
  register: minio_kes_tmp_vault_client_cert
  environment:
      VAULT_CACERT: "{{ hashicorp_vault_kv2_inventory.hvac_client_configuration.verify }}"
      VAULT_CLIENT_CERT: "{{ hashicorp_vault_kv2_inventory.hvac_client_configuration.cert[0] }}"
      VAULT_CLIENT_KEY: "{{ hashicorp_vault_kv2_inventory.hvac_client_configuration.cert[1] }}"

- name: Minio | Server | Minio Server Certificate
  become: false
  delegate_facts: true
  delegate_to: localhost
  community.hashi_vault.vault_write:
      url: "{{ hashicorp_vault_kv2_inventory.hvac_client_configuration.url }}"
      path: pki/issue/server_certificate
      token: "{{ hashicorp_vault_kv2_inventory.hvac_token }}"
      validate_certs: true
      data:
          common_name: "{{ inventory_hostname }}"
          alt_names: "{{ minio_server_hostnames | join(',') }}"
          ip_sans: "{{ minio_server_ips | join(',') }}"
  register: minio_server_tmp_certificate
  environment:
      VAULT_CACERT: "{{ hashicorp_vault_kv2_inventory.hvac_client_configuration.verify }}"
      VAULT_CLIENT_CERT: "{{ hashicorp_vault_kv2_inventory.hvac_client_configuration.cert[0] }}"
      VAULT_CLIENT_KEY: "{{ hashicorp_vault_kv2_inventory.hvac_client_configuration.cert[1] }}"

- name: Minio | KES/Server | Write Server Certificate
  ansible.builtin.copy:
      content: "{{ item.content }}"
      dest: "{{ item.dest }}"
      owner: "{{ item.owner }}"
      group: "{{ item.group }}"
      mode: "0777"
  loop:
      - content: "{{ minio_kes_tmp_server_cert.data.data.certificate }}\n\
            {{ minio_kes_tmp_server_cert.data.data.ca_chain | join('\n') }}"
        dest: "{{ minio_kes_server_cert }}"
        owner: "{{ minio_kes_user }}"
        group: "{{ minio_kes_group }}"
      - content: "{{ minio_kes_tmp_server_cert.data.data.private_key }}"
        dest: "{{ minio_kes_server_key }}"
        owner: "{{ minio_kes_user }}"
        group: "{{ minio_kes_group }}"
      - content: "{{ minio_kes_tmp_server_cert.data.data.ca_chain | join('\n') }}"
        dest: "{{ minio_kes_server_ca }}"
        owner: "{{ minio_kes_user }}"
        group: "{{ minio_kes_group }}"

      - content: "{{ minio_kes_tmp_vault_client_cert.data.data.certificate }}\n\
            {{ minio_kes_tmp_vault_client_cert.data.data.ca_chain | join('\n') }}"
        dest: "{{ minio_kes_vault_client_cert }}"
        owner: "{{ minio_kes_user }}"
        group: "{{ minio_kes_group }}"
      - content: "{{ minio_kes_tmp_vault_client_cert.data.data.private_key }}"
        dest: "{{ minio_kes_vault_client_key }}"
        owner: "{{ minio_kes_user }}"
        group: "{{ minio_kes_group }}"
      - content: "{{ minio_kes_tmp_vault_client_cert.data.data.ca_chain | join('\n') }}"
        dest: "{{ minio_kes_vault_ca_cert }}"
        owner: "{{ minio_kes_user }}"
        group: "{{ minio_kes_group }}"

      - content: "{{ minio_vault_tmp_admin_client_cert.data.data.certificate }}\n\
            {{ minio_vault_tmp_admin_client_cert.data.data.ca_chain | join('\n') }}"
        dest: "{{ minio_server_kes_client_cert }}"
        owner: "{{ minio_server_user }}"
        group: "{{ minio_server_group }}"
      - content: "{{ minio_vault_tmp_admin_client_cert.data.data.private_key }}"
        dest: "{{ minio_server_kes_client_key }}"
        owner: "{{ minio_server_user }}"
        group: "{{ minio_server_group }}"
      - content: "{{ minio_vault_tmp_admin_client_cert.data.data.certificate }}\n\
            {{ minio_vault_tmp_admin_client_cert.data.data.ca_chain | join('\n') }}"
        dest: "{{ minio_server_kes_client_ca }}"
        owner: "{{ minio_server_user }}"
        group: "{{ minio_server_group }}"
      - content: "{{ minio_server_tmp_certificate.data.data.certificate }}\n\
            {{ minio_server_tmp_certificate.data.data.ca_chain | join('\n') }}"
        dest: "{{ minio_server_cert }}"
        owner: "{{ minio_server_user }}"
        group: "{{ minio_server_group }}"
      - content: "{{ minio_server_tmp_certificate.data.data.private_key }}"
        dest: "{{ minio_server_key }}"
        owner: "{{ minio_server_user }}"
        group: "{{ minio_server_group }}"
      - content: "{{ minio_server_tmp_certificate.data.data.ca_chain | join('\n') }}"
        dest: "{{ minio_server_ca }}"
        owner: "{{ minio_server_user }}"
        group: "{{ minio_server_group }}"
