---
- name: Minio | Server | Create group
  ansible.builtin.group:
      name: "{{ minio_server_group }}"
      state: present
      system: true
  register: minio_server_tmp_group_creation

- name: Minio | Server | Create User
  ansible.builtin.user:
      name: "{{ minio_server_user }}"
      group: "{{ minio_server_group }}"
      state: present
      create_home: true
      system: true
      shell: /bin/false
      home: "{{ minio_server_home }}"
  register: minio_server_tmp_user_creation

- name: Minio | Server | Download binary
  ansible.builtin.get_url:
      dest: "/usr/local/bin/minio"
      mode: "0755"
      owner: root
      group: root
      checksum: "sha256:{{ minio_server_bin_info_map[ansible_architecture]['sha256sum'][minio_server_version] }}"
      url: "https://dl.min.io/server/minio/release/linux-\
          {{ minio_server_bin_info_map[ansible_architecture]['minio_server_arch'] }}/archive/minio.\
          {{ minio_server_version }}"

- name: Minio | Server | Create Directories
  ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      owner: "{{ minio_server_user }}"
      group: "{{ minio_server_group }}"
      mode: "0777"
  loop:
      - "{{ minio_server_certs_dir }}"
      - "{{ minio_server_certs_dir }}/CAs"
      - "{{ minio_server_data_dir }}"

- name: Minio | Server | Certs
  ansible.builtin.import_tasks:
      file: certs.yml

- name: Minio | Server | Create Env File
  ansible.builtin.copy:
      content: |+
          MINIO_KMS_KES_ENDPOINT=https://{{ minio_kes_hostname }}:{{ minio_kes_port }}
          MINIO_KMS_KES_KEY_FILE={{ minio_server_kes_client_key }}
          MINIO_KMS_KES_CERT_FILE={{ minio_server_kes_client_cert }}
          MINIO_KMS_KES_CAPATH={{ minio_server_kes_client_ca }}
          MINIO_KMS_KES_KEY_NAME=default
          MINIO_ROOT_USER={{ minio_server_root_user }}
          MINIO_ROOT_PASSWORD={{ minio_server_root_password }}
          MINIO_REGION=us-east-1
          MINIO_VOLUMES={{ minio_server_data_dir }}
          MINIO_OPTS="--address ':{{ minio_server_port }}' --console-address ':{{ minio_server_console_port }}' --certs-dir {{ minio_server_certs_dir }}"
      dest: "{{ minio_env_file }}"
      owner: "{{ minio_server_user }}"
      group: "{{ minio_server_group }}"
      mode: "0777"

- name: Minio | Server | Enable UFW
  community.general.ufw:
      rule: allow
      port: "{{ item }}"
      proto: tcp
      comment: "Minio Server"
  loop:
      - "{{ minio_server_port }}"
      - "{{ minio_server_console_port }}"

- name: Minio | KES/Server | Create Systemd Service
  ansible.builtin.template:
      src: "templates/{{ minio_server_systemd_service_name }}.j2"
      dest: "/etc/systemd/system/{{ minio_server_systemd_service_name }}"
      owner: root
      group: root
      mode: "0644"

- name: Minio | KES/Server | Start Systemd Service
  ansible.builtin.systemd_service:
      name: "{{ minio_server_systemd_service_name }}"
      state: restarted
      daemon_reload: true
      daemon_reexec: true
      enabled: true
