---
- name: Minio | Assert | Set minio_server_kes_secret_id_vault
  ansible.builtin.set_fact:
      minio_server_kes_secret_id_vault: "{{ minio_server_kes_secret_id_vault | d(inventory_hostname)
          | mandatory }}"

- name: Minio | Assert | Get KES Admin Key Id from Vault
  become: false
  delegate_facts: true
  delegate_to: localhost
  community.hashi_vault.vault_kv2_get:
      url: "{{ hashicorp_vault_kv2_inventory.hvac_client_configuration.url }}"
      engine_mount_point: "secret"
      path: "minio/kes/servers/{{ minio_server_kes_secret_id_vault }}/config"
      token: "{{ hashicorp_vault_kv2_inventory.hvac_token }}"
      validate_certs: true
  register: minio_server_kes_secret_dict
  environment:
      VAULT_CACERT: "{{ hashicorp_vault_kv2_inventory.hvac_client_configuration.verify }}"
      VAULT_CLIENT_CERT: "{{ hashicorp_vault_kv2_inventory.hvac_client_configuration.cert[0] }}"
      VAULT_CLIENT_KEY: "{{ hashicorp_vault_kv2_inventory.hvac_client_configuration.cert[1] }}"

- name: Minio | Assert | minio_server_hostnames
  ansible.builtin.assert:
      that:
          - minio_server_hostnames | type_debug == 'list'
          - minio_server_hostnames | length > 0
      fail_msg: "minio_server_hostnames must be a list with at least one element"

- name: Minio | Assert | minio_server_ips
  ansible.builtin.assert:
      that:
          - minio_server_ips | type_debug == 'list'
          - minio_server_ips | length > 0
      fail_msg: "minio_server_ips must be a list with at least one element"

- name: Minio | Assert | minio_server_kes_endpoint hostname
  ansible.builtin.assert:
      that:
          - |+
              minio_server_kes_endpoint | urlsplit('hostname')
              in
              (minio_server_kes_secret_dict.secret.hostnames + minio_server_kes_secret_dict.secret.ips)
      fail_msg: "minio_server_kes_endpoint must be a valid URL with hostname or IP address"

- name: Minio | Assert | minio_server_kes_endpoint port
  ansible.builtin.assert:
      that:
          - minio_server_kes_endpoint | urlsplit('port') == minio_server_kes_secret_dict.secret.port
